name: Publish Docker image to GitHub Package Registry
on:
  push:
    branches:
      - master

env:
  KNATIVE_VERSION: 0.9.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Publish knative/serving/hello-world to GPR
      uses: evry-ace/github-action-gpr-docker-publish@master
      with:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: hello-world-go
        IMAGE_TAG: 0.9.0
        DOCKERFILE_PATH: knative/docs/serving/samples/hello-world/helloworld-go/Dockerfile
        BUILD_CONTEXT: knative/docs/serving/samples/hello-world/helloworld-go

    - name: Publish knative/serving/rest-api-go to GPR
      uses: evry-ace/github-action-gpr-docker-publish@master
      with:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: rest-api-go
        IMAGE_TAG: 0.9.0
        DOCKERFILE_PATH: knative/docs/serving/samples/rest-api-go/Dockerfile
        BUILD_CONTEXT: knative/
