name: Publish Docker image to Docker Hub
on:
  push:
    branches:
      - master

env:
  KNATIVE_VERSION: 0.9.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Publish knative/serving/hello-world to DH
      uses: evry-ace/github-action-dh-publish@master
      with:
        name: evryace/knative-serving-hello-world-go:0.9.0
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        dockerfile: knative/docs/serving/samples/hello-world/helloworld-go/Dockerfile
        workdir: knative/docs/serving/samples/hello-world/helloworld-go

    - name: Publish knative/serving/rest-api-go to DH
      uses: evry-ace/github-action-dh-publish@master
      with:
        name: evryace/knative-serving-rest-api-go:0.9.0
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        dockerfile: knative/docs/serving/samples/rest-api-go/Dockerfile
        workdir: knative
